title: Robert Riemer
logo: "C:\Users\rmr1q.000\Pictures\Camera Roll\Headshot 1 Circle.jpg"
description: Data Analyst with a background in collaboration and public speaking.
show_downloads: true
theme: jekyll-theme-minimal
