title: Robert Riemer
#url: 'https://data-rob.github.io/'
logo: Headshot 1 Circle.jpg
description: Data Analyst with a background in collaboration and public speaking.
show_downloads: false
theme: gem "jekyll-theme-minimal"

#Layout
show_social: true
show_excerpts: true
show_frame: true
show_sidebar: true


